In [4]:
#python program for creating of array

import numpy as np
arr = np.array([1,2,3,4])
print("Array With Rank 1: \n",arr)

arr = np.array([[1,2,3,4],
              [9,8,7,6]])
print("Array With Rank 2: \n",arr)


#creating an array from tuple

arr = np.array((3,5,6,7))
print("\nArray created using "
     "passed tuple :\n",arr)

Array With Rank 1: 
 [1 2 3 4]
Array With Rank 2: 
 [[1 2 3 4]
 [9 8 7 6]]

Array created using passed tuple :
 [3 5 6 7]


In [20]:
  #  ****Accessing the array index*****
    #indexing in nump
    import numpy as np
    arr = np.array([[1,2,3,4],
                    [12,3,45,6],
                    [1,2,4,5],
                    [2,5,6,7]])
    
    print("Initial array:")
    print(arr)
    
    
    
    #printing a range of array
    sliced_arr=arr[:2,::2]
    print("Array with first 2 row and columns alternate columns(0 nad 2):\n",sliced_arr)
    
    
    index_arr=arr[[1,2,1,3],
                 [2,3,45,6]]
    print("\n element at indices (1,2),(2,3),(1,45),(3,6):\n",index_arr)
                

IndentationError: unexpected indent (<ipython-input-20-56f82ddc2b71>, line 3)

In [25]:
#basic operation  on single array
import numpy as np
a = np.array([[1,2],
            [3,4]])
b= np.array([[2,5],
           [6,3]])
#adding 1 to every element
print("adding 1 to every element :",a+1)
print("subtracting 2 element to each element :",b-2)


#sum of element
#Performing Unary operations
print("\n Sum of all array element is :",a.sum())


#Adding two arrays
#performing binary operations
print("\nArray sum :\n",a+b)

print("array is of type",type(a))

print("\n no.of dimention",a.ndim)

print("\n shape of array ",a.shape)
print("\n size of array",b.size)

print("Array stores element of type",b.dtype)





adding 1 to every element : [[2 3]
 [4 5]]
subtracting 2 element to each element : [[0 3]
 [4 1]]

 Sum of all array element is : 10

Array sum :
 [[3 7]
 [9 7]]
array is of type <class 'numpy.ndarray'>

 no.of dimention 2

 shape of array  (2, 2)

 size of array 4
Array stores element of type int64
